/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure

  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    "intro",
    {
      type: 'category',
      label: 'User Guide',
      items: [
        'user_guide/installation',
        'user_guide/basics',
        'user_guide/features',
        'user_guide/all',
      ],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      items: [
        'developer_guide/running',
        'developer_guide/self-hosted',
        'developer_guide/repl',
        'developer_guide/ci',
        'developer_guide/git',
        'developer_guide/storybook',
        'developer_guide/resources',
        'developer_guide/architecture',
      ],
    },
    "faq",
  ],

};

module.exports = sidebars;
